type: chart
rootfs:
  - image: samsung_cnct/golang-container
    buildArgs: 
      - arg: DEP_VERSION
        value: "v0.4.1"
      - arg: GOSU_VERSION
        value: "1.10"
    context: golang-container
    dockerContext: rootfs/golang-container
configs:
  - stage: 
      tests:
        - script: scripts/stageTest.sh
          shell: /usr/local/bin/bash
